---
title: "Untitled"
author: "Anna"
date: "2024-11-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


Importing data saved as rds (r file format)

```{r}
library(tidyverse)
```

```{r}
here::here("data/human_data_selection_dedup.rds")
human_selection <- readRDS(here::here("data", "human_data_selection_dedup.rds")
                           )
```

 #connection to the database in WHONET
 
```{r}
#install.packages("RSQLite")
library(RSQLite)
```

 
```{r}
sqlite_path <- "C:/WHONET/Data/TZA-INIKA_TZ-2024.sqlite"
sqlite_path
dbconn <- DBI::dbConnect(
  RSQLite::SQLite(),
  sqlite_path
)
```
```{r}
dbconn
```

```{r}
dbListTables(dbconn)
```
```{r}
mydata_recipie <- tbl(dbconn, "isolates")
str(mydata_recipie)
head(mydata_recipie)
```

```{r}
show_query(mydata_recipie)
```

```{r}
mydata <- mydata_recipie %>%
  collect()
```

```{r}
mydata %>% head() %>% print(width = Inf)
human_selection %>% head() %>% print(width = Inf)
```

```{r}
#my_innerjoin <- 
  human_selection %>% 
  # selecting few columns for testing
  #  this can be used to do a short selection of the columns if not all are required
  # select(1:3) %>% 
  dplyr::inner_join(mydata, by = c("INIKA_OH_TZ_ID" = "PATIENT_ID")) %>%
  head() %>%
  view()
```

would it work?

```{r}
mydata %>%
  dplyr::inner_join(
    human_selection %>% select(1:3),
    by = c("PATIENT_ID" = "INIKA_OH_TZ_ID")
    ) %>%
  head() %>%
  view() 
```


 